In [15]:
import numpy as np

In [16]:
l=[1,2,3,4]

In [17]:
ar=np.array(l)

In [18]:
ar

array([1, 2, 3, 4])

In [19]:
type(ar)

numpy.ndarray

In [20]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [21]:
np.asarray(l)

array([1, 2, 3, 4])

In [22]:
a=[2,4,5,5]

In [23]:
np.asanyarray(a)

array([2, 4, 5, 5])

In [24]:
b= np.matrix(l)

In [25]:
b

matrix([[1, 2, 3, 4]])

In [26]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [28]:
a=np.array(l)

In [29]:
a

array([1, 2, 3, 4])

In [31]:
c=a

In [32]:
a

array([1, 2, 3, 4])

In [33]:
a

array([1, 2, 3, 4])

In [34]:
c[0]=23

In [35]:
c

array([23,  2,  3,  4])

In [36]:
a

array([23,  2,  3,  4])

In [37]:
d=np.copy(a)

In [38]:
d

array([23,  2,  3,  4])

In [39]:
a

array([23,  2,  3,  4])

In [40]:
a[1]=121

In [41]:
a

array([ 23, 121,   3,   4])

In [42]:
d

array([23,  2,  3,  4])

In [44]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [45]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [46]:
iterable=(i*i for i in range (4))

In [47]:
np.fromiter(iterable,float)

array([0., 1., 4., 9.])

In [48]:
np.fromstring('2331 213',sep=' ')

array([2331.,  213.])

In [50]:
np.fromstring('2,3',sep=',')

array([2., 3.])

In [51]:
# numpy -Data types

In [52]:
l=[2,3,4,55,]

In [53]:
ar=np.array(l)

In [54]:
ar

array([ 2,  3,  4, 55])

In [55]:
ar.ndim

1

In [56]:
ar2=np.array([[1,2,3,4],[2,2,42,34]])

In [57]:
ar2.ndim

2

In [58]:
ar.size

4

In [59]:
ar2.size

8

In [60]:
ar

array([ 2,  3,  4, 55])

In [61]:
ar2

array([[ 1,  2,  3,  4],
       [ 2,  2, 42, 34]])

In [62]:
ar.shape

(4,)

In [63]:
ar2.shape

(2, 4)

In [64]:
ar.dtype

dtype('int64')

In [65]:
ar2.dtype

dtype('int64')

In [70]:
ar22=np.array([( 1.32,  2, 433,  14),
       ( 21,  2, 42, 34)])

In [71]:
ar22

array([[  1.32,   2.  , 433.  ,  14.  ],
       [ 21.  ,   2.  ,  42.  ,  34.  ]])

In [73]:
ar22.dtype

dtype('float64')

In [74]:
range(3)

range(0, 3)

In [75]:
list(range(3))

[0, 1, 2]

In [76]:
list(range(0.12,2.1))

TypeError: 'float' object cannot be interpreted as an integer

In [77]:
np.arange(2.1,4.5)

array([2.1, 3.1, 4.1])

In [82]:
list(np.arange(2.1,4.5,.5))

[2.1, 2.6, 3.1, 3.6, 4.1]

In [84]:
np.linspace(2,5,5)

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [85]:
np.zeros(4)

array([0., 0., 0., 0.])

In [86]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [89]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [91]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [93]:
on=np.ones((2,5,6))

In [94]:
on+4

array([[[5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.]]])

In [95]:
on*2

array([[[2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.]]])

In [98]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [99]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
np.linspace(2,31,10)

array([ 2.        ,  5.22222222,  8.44444444, 11.66666667, 14.88888889,
       18.11111111, 21.33333333, 24.55555556, 27.77777778, 31.        ])

In [101]:
np.logspace(2,5,21,base=4)

array([  16.        ,   19.69831061,   24.25146506,   29.85705573,
         36.75834736,   45.254834  ,   55.71523605,   68.5935016 ,
         84.44850629,  103.96830673,  128.        ,  157.58648491,
        194.01172051,  238.85644583,  294.06677888,  362.03867197,
        445.72188841,  548.74801282,  675.58805032,  831.74645387,
       1024.        ])

In [103]:
arr=np.random.randn(3,5)

In [104]:
import pandas as pd

In [105]:
pd.DataFrame(arr)

0         1         2         3         4
0 -0.648592  0.477049  0.778673  0.814280 -2.069031
1 -0.816561  0.103085  0.276029  0.369515 -0.667916
2  0.908594 -0.478317 -2.286136  0.329837 -2.064003

In [106]:
np.random.randn(3,5)

array([[ 1.44610152, -0.2171403 ,  0.85193041, -1.61261346, -0.62717969],
       [-0.71569432, -1.53739383, -1.03435349, -0.54757596,  0.27423634],
       [ 1.493855  , -0.0511812 , -0.85128168, -0.51709485,  0.76084861]])

In [110]:
np.random.randint(2,50,(3,4))

array([[23, 14, 31, 35],
       [19, 17, 27, 31],
       [43, 20, 46,  3]])

In [114]:
pd.DataFrame(np.random.randint(2,50,(325,23))).to_csv('test.csv')

In [115]:
ar=np.random.rand(4,5)

In [116]:
ar

array([[0.12733311, 0.16554135, 0.08010938, 0.44674223, 0.94700991],
       [0.92825365, 0.17007243, 0.60260598, 0.51584845, 0.30685109],
       [0.59999348, 0.19697225, 0.49965123, 0.7013718 , 0.75225073],
       [0.5770373 , 0.34585762, 0.96127209, 0.21022593, 0.88140595]])

In [122]:
arr1=ar.reshape(10,-324)

In [123]:
arr1

array([[0.12733311, 0.16554135],
       [0.08010938, 0.44674223],
       [0.94700991, 0.92825365],
       [0.17007243, 0.60260598],
       [0.51584845, 0.30685109],
       [0.59999348, 0.19697225],
       [0.49965123, 0.7013718 ],
       [0.75225073, 0.5770373 ],
       [0.34585762, 0.96127209],
       [0.21022593, 0.88140595]])

In [125]:
arr1[1][1]

0.4467422300806644

In [130]:
arr1[2:5,1]

array([0.92825365, 0.60260598, 0.30685109])

In [142]:
arr= np.random.randint(3,100,(4,5))

In [144]:
arr

array([[60, 42, 94, 76, 16],
       [96, 21, 68, 40, 79],
       [51, 38, 61, 12, 78],
       [ 8, 30, 30, 24, 37]])

In [145]:
arr>50

array([[ True, False,  True,  True, False],
       [ True, False,  True, False,  True],
       [ True, False,  True, False,  True],
       [False, False, False, False, False]])

In [146]:
arr

array([[60, 42, 94, 76, 16],
       [96, 21, 68, 40, 79],
       [51, 38, 61, 12, 78],
       [ 8, 30, 30, 24, 37]])

In [149]:
arr[2:4,[1,2]]

array([[38, 61],
       [30, 30]])

In [150]:
arr[0][0]=300

In [151]:
arr

array([[300,  42,  94,  76,  16],
       [ 96,  21,  68,  40,  79],
       [ 51,  38,  61,  12,  78],
       [  8,  30,  30,  24,  37]])

In [154]:
arr1= np.random.randint(3,4,(4,4))
arr2= np.random.randint(1,3,(4,4))

In [155]:
arr1

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [156]:
arr2

array([[1, 2, 2, 2],
       [2, 2, 1, 2],
       [1, 2, 2, 1],
       [1, 2, 1, 2]])

In [157]:
arr1+arr2

array([[4, 5, 5, 5],
       [5, 5, 4, 5],
       [4, 5, 5, 4],
       [4, 5, 4, 5]])

In [158]:
arr1-arr2

array([[2, 1, 1, 1],
       [1, 1, 2, 1],
       [2, 1, 1, 2],
       [2, 1, 2, 1]])

In [159]:
arr1/arr2

array([[3. , 1.5, 1.5, 1.5],
       [1.5, 1.5, 3. , 1.5],
       [3. , 1.5, 1.5, 3. ],
       [3. , 1.5, 3. , 1.5]])

In [160]:
arr1*arr2

array([[3, 6, 6, 6],
       [6, 6, 3, 6],
       [3, 6, 6, 3],
       [3, 6, 3, 6]])

In [161]:
arr1@arr2

array([[15, 24, 18, 21],
       [15, 24, 18, 21],
       [15, 24, 18, 21],
       [15, 24, 18, 21]])

In [162]:
arr1/0

/tmp/ipykernel_126/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [163]:
arr1

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [164]:
arr1+100

array([[103, 103, 103, 103],
       [103, 103, 103, 103],
       [103, 103, 103, 103],
       [103, 103, 103, 103]])

In [165]:
arr1**2

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [166]:
# Numpy- Broadcasting

In [168]:
arr=np.zeros((3,3))

In [169]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [173]:
row=np.array([1,2,3])

In [174]:
row

array([1, 2, 3])

In [175]:
arr+row

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [177]:
row.T

array([1, 2, 3])

In [178]:
col=np.array([[1,2,3]])

In [181]:
col.T+arr

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [184]:
arr1=np.random.randint(1,10,(3,4))

In [185]:
arr1

array([[9, 5, 8, 7],
       [4, 8, 7, 2],
       [5, 8, 9, 3]])

In [187]:
np.sqrt(arr1)

array([[3.        , 2.23606798, 2.82842712, 2.64575131],
       [2.        , 2.82842712, 2.64575131, 1.41421356],
       [2.23606798, 2.82842712, 3.        , 1.73205081]])

In [188]:
np.exp(arr1)

array([[8.10308393e+03, 1.48413159e+02, 2.98095799e+03, 1.09663316e+03],
       [5.45981500e+01, 2.98095799e+03, 1.09663316e+03, 7.38905610e+00],
       [1.48413159e+02, 2.98095799e+03, 8.10308393e+03, 2.00855369e+01]])

In [189]:
np.log10(arr1)

array([[0.95424251, 0.69897   , 0.90308999, 0.84509804],
       [0.60205999, 0.90308999, 0.84509804, 0.30103   ],
       [0.69897   , 0.90308999, 0.95424251, 0.47712125]])