In [1]:
# Sort,search & Counting Function

In [2]:
import numpy as np

In [5]:
arr=np.array([1,3,456,232,6,7,88,8,9])

In [7]:
arr

array([  1,   3, 456, 232,   6,   7,  88,   8,   9])

In [8]:
np.sort(arr)

array([  1,   3,   6,   7,   8,   9,  88, 232, 456])

In [10]:
np.searchsorted(arr,23)

9

In [12]:
arr1=np.array([32,2,9,0,12,4,56,0,5,0,9,0])

In [13]:
arr1

array([32,  2,  9,  0, 12,  4, 56,  0,  5,  0,  9,  0])

In [14]:
np.count_nonzero(arr1)

8

In [16]:
arr

array([  1,   3, 456, 232,   6,   7,  88,   8,   9])

In [17]:
np.where(arr>7)

(array([2, 3, 6, 7, 8]),)

In [19]:
np.extract(arr>8,arr)

array([456, 232,  88,   9])

In [20]:
#NumPy - Byte Swaping

In [21]:
arr

array([  1,   3, 456, 232,   6,   7,  88,   8,   9])

In [22]:
arr.byteswap()

array([   72057594037927936,   216172782113783808, -4034943791147253760,
       -1729382256910270464,   432345564227567616,   504403158265495552,
        6341068275337658368,   576460752303423488,   648518346341351424])

In [23]:
# NumPy - Copies 7 Views

In [24]:
arr

array([  1,   3, 456, 232,   6,   7,  88,   8,   9])

In [25]:
a=np.copy(arr)

In [26]:
a

array([  1,   3, 456, 232,   6,   7,  88,   8,   9])

In [34]:
b=arr.view()

In [35]:
b=arr

In [28]:
b

array([  1,   3, 456, 232,   6,   7,  88,   8,   9])

In [30]:
b[0]=35

In [31]:
b

array([ 35,   3, 456, 232,   6,   7,  88,   8,   9])

In [32]:
arr

array([ 35,   3, 456, 232,   6,   7,  88,   8,   9])

In [46]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [52]:
import numpy.matlib as nm

In [55]:
nm.zeros(4)

matrix([[0., 0., 0., 0.]])

In [56]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [58]:
# NumPy - Linear algebra

In [75]:
arr1= np.random.randint(1,10,(4,5))
arr2= np.random.randint(1,7,(5,2))

In [76]:
arr1

array([[8, 7, 4, 3, 8],
       [2, 5, 3, 2, 7],
       [4, 6, 7, 5, 3],
       [3, 9, 6, 6, 4]])

In [77]:
arr2

array([[5, 2],
       [1, 1],
       [2, 3],
       [2, 1],
       [2, 2]])

In [78]:
np.dot(arr1,arr2)

array([[77, 54],
       [39, 34],
       [56, 46],
       [56, 47]])

In [79]:
arr1@arr2

array([[77, 54],
       [39, 34],
       [56, 46],
       [56, 47]])