In [1]:
# NumPy - Array manipulation

In [2]:
import numpy as np

In [3]:
arr=np.random.randint(1,10,(3,4))

In [4]:
arr

array([[7, 1, 1, 3],
       [1, 3, 6, 9],
       [6, 3, 4, 2]])

In [5]:
arr.reshape(3,4)

array([[7, 1, 1, 3],
       [1, 3, 6, 9],
       [6, 3, 4, 2]])

In [7]:
arr.reshape(2,-122)

array([[7, 1, 1, 3, 1, 3],
       [6, 9, 6, 3, 4, 2]])

In [8]:
arr.T

array([[7, 1, 6],
       [1, 3, 3],
       [1, 6, 4],
       [3, 9, 2]])

In [9]:
arr

array([[7, 1, 1, 3],
       [1, 3, 6, 9],
       [6, 3, 4, 2]])

In [10]:
arr.flatten()

array([7, 1, 1, 3, 1, 3, 6, 9, 6, 3, 4, 2])

In [11]:
arr1=np.array([1,3,4,5])

In [13]:
arr1.ndim

1

In [16]:
np.expand_dims(arr1,axis=1)

array([[1],
       [3],
       [4],
       [5]])

In [17]:
np.expand_dims(arr1,axis=0)

array([[1, 3, 4, 5]])

In [18]:
arr

array([[7, 1, 1, 3],
       [1, 3, 6, 9],
       [6, 3, 4, 2]])

In [19]:
np.squeeze(arr)

array([[7, 1, 1, 3],
       [1, 3, 6, 9],
       [6, 3, 4, 2]])

In [20]:
data=np.array([[2],[3],[5]])

In [21]:
data

array([[2],
       [3],
       [5]])

In [22]:
np.squeeze(data)

array([2, 3, 5])

In [23]:
np.repeat(arr1,3)

array([1, 1, 1, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [24]:
np.roll(arr1,2)

array([4, 5, 1, 3])

In [25]:
arr1

array([1, 3, 4, 5])

In [26]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [27]:
#NumPy - Binary operators

In [28]:
arr1=np.random.randint(1,10,(4,5))
arr2=np.random.randint(1,10,(4,5))

In [29]:
arr1

array([[7, 1, 9, 2, 1],
       [4, 4, 3, 4, 8],
       [1, 1, 4, 4, 5],
       [8, 7, 2, 6, 3]])

In [30]:
arr2

array([[4, 4, 2, 7, 2],
       [6, 9, 4, 9, 7],
       [2, 3, 9, 9, 1],
       [2, 9, 3, 4, 5]])

In [31]:
arr1+arr2

array([[11,  5, 11,  9,  3],
       [10, 13,  7, 13, 15],
       [ 3,  4, 13, 13,  6],
       [10, 16,  5, 10,  8]])

In [32]:
arr1*arr2

array([[28,  4, 18, 14,  2],
       [24, 36, 12, 36, 56],
       [ 2,  3, 36, 36,  5],
       [16, 63,  6, 24, 15]])

In [33]:
arr1/arr2

array([[1.75      , 0.25      , 4.5       , 0.28571429, 0.5       ],
       [0.66666667, 0.44444444, 0.75      , 0.44444444, 1.14285714],
       [0.5       , 0.33333333, 0.44444444, 0.44444444, 5.        ],
       [4.        , 0.77777778, 0.66666667, 1.5       , 0.6       ]])

In [34]:
arr1-arr2

array([[ 3, -3,  7, -5, -1],
       [-2, -5, -1, -5,  1],
       [-1, -2, -5, -5,  4],
       [ 6, -2, -1,  2, -2]])

In [35]:
arr1%arr2

array([[3, 1, 1, 2, 1],
       [4, 4, 3, 4, 1],
       [1, 1, 4, 4, 0],
       [0, 7, 2, 2, 3]])

In [36]:
arr1**arr2

array([[    2401,        1,       81,      128,        1],
       [    4096,   262144,       81,   262144,  2097152],
       [       1,        1,   262144,   262144,        5],
       [      64, 40353607,        8,     1296,      243]])

In [37]:
arr1

array([[7, 1, 9, 2, 1],
       [4, 4, 3, 4, 8],
       [1, 1, 4, 4, 5],
       [8, 7, 2, 6, 3]])

In [38]:
arr2

array([[4, 4, 2, 7, 2],
       [6, 9, 4, 9, 7],
       [2, 3, 9, 9, 1],
       [2, 9, 3, 4, 5]])

In [39]:
-arr1

array([[-7, -1, -9, -2, -1],
       [-4, -4, -3, -4, -8],
       [-1, -1, -4, -4, -5],
       [-8, -7, -2, -6, -3]])

In [40]:
arr1|arr2

array([[ 7,  5, 11,  7,  3],
       [ 6, 13,  7, 13, 15],
       [ 3,  3, 13, 13,  5],
       [10, 15,  3,  6,  7]])

In [41]:
arr1>arr2

array([[ True, False,  True, False, False],
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       [ True, False, False,  True, False]])

In [42]:
# NumPy- String Function

In [44]:
arr=np.array(['mithi','kumar'])

In [45]:
arr

array(['mithi', 'kumar'], dtype='<U5')

In [46]:
np.char.upper(arr)

array(['MITHI', 'KUMAR'], dtype='<U5')

In [47]:
np.char.title(arr)

array(['Mithi', 'Kumar'], dtype='<U5')

In [48]:
np.char.capitalize(arr)

array(['Mithi', 'Kumar'], dtype='<U5')

In [49]:
#NumPy - Mathmatical Function

In [50]:
arr1

array([[7, 1, 9, 2, 1],
       [4, 4, 3, 4, 8],
       [1, 1, 4, 4, 5],
       [8, 7, 2, 6, 3]])

In [52]:
np.sin(arr1)

array([[ 0.6569866 ,  0.84147098,  0.41211849,  0.90929743,  0.84147098],
       [-0.7568025 , -0.7568025 ,  0.14112001, -0.7568025 ,  0.98935825],
       [ 0.84147098,  0.84147098, -0.7568025 , -0.7568025 , -0.95892427],
       [ 0.98935825,  0.6569866 ,  0.90929743, -0.2794155 ,  0.14112001]])

In [53]:
np.cos(arr1)

array([[ 0.75390225,  0.54030231, -0.91113026, -0.41614684,  0.54030231],
       [-0.65364362, -0.65364362, -0.9899925 , -0.65364362, -0.14550003],
       [ 0.54030231,  0.54030231, -0.65364362, -0.65364362,  0.28366219],
       [-0.14550003,  0.75390225, -0.41614684,  0.96017029, -0.9899925 ]])

In [54]:
np.tan(arr1)

array([[ 0.87144798,  1.55740772, -0.45231566, -2.18503986,  1.55740772],
       [ 1.15782128,  1.15782128, -0.14254654,  1.15782128, -6.79971146],
       [ 1.55740772,  1.55740772,  1.15782128,  1.15782128, -3.38051501],
       [-6.79971146,  0.87144798, -2.18503986, -0.29100619, -0.14254654]])

In [55]:
np.log10(arr1)

array([[0.84509804, 0.        , 0.95424251, 0.30103   , 0.        ],
       [0.60205999, 0.60205999, 0.47712125, 0.60205999, 0.90308999],
       [0.        , 0.        , 0.60205999, 0.60205999, 0.69897   ],
       [0.90308999, 0.84509804, 0.30103   , 0.77815125, 0.47712125]])

In [56]:
np.exp(arr1)

array([[1.09663316e+03, 2.71828183e+00, 8.10308393e+03, 7.38905610e+00,
        2.71828183e+00],
       [5.45981500e+01, 5.45981500e+01, 2.00855369e+01, 5.45981500e+01,
        2.98095799e+03],
       [2.71828183e+00, 2.71828183e+00, 5.45981500e+01, 5.45981500e+01,
        1.48413159e+02],
       [2.98095799e+03, 1.09663316e+03, 7.38905610e+00, 4.03428793e+02,
        2.00855369e+01]])

In [58]:
np.power(arr1,2)

array([[49,  1, 81,  4,  1],
       [16, 16,  9, 16, 64],
       [ 1,  1, 16, 16, 25],
       [64, 49,  4, 36,  9]])

In [59]:
np.mean(arr1)

4.2

In [60]:
np.median(arr1)

4.0

In [61]:
np.std(arr1)

2.5019992006393608

In [62]:
np.var(arr1)

6.26

In [63]:
np.min(arr1)

1

In [64]:
np.max(arr1)

9